### ISSUE TITLE
using default kubeadmin (kube:admin) does not appear to work

### ISSUE THREAD

**Issue by rayashworth** [open-cluster-management/cluster-keeper#26] opened 2021-03-05 20:15 UTC
Trying to test using kubeadmin token.

Creating context ck
Creating ServiceAccount kube:admin
Error from server (NotFound): serviceaccounts "kube:admin" not found
Logging in as ServiceAccount kube:admin
error: The token provided is invalid or expired.

**Comment by KevinFCormier** [comment] 2021-03-05 21:44
Duplicate of #27

**Closed by KevinFCormier** 2021-03-05 21:44 UTC
